-- CreateTable
CREATE TABLE "TB_TEAMS" (
    "id" SERIAL NOT NULL,
    "titleTeam" TEXT NOT NULL,
    "userId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TB_TEAMS_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "TB_TEAMS" ADD CONSTRAINT "TB_TEAMS_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TB_USERS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
