-- CreateTable
CREATE TABLE "TB_USERS" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "imageUrl" TEXT NOT NULL,

    CONSTRAINT "TB_USERS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_TEAMS" (
    "id" SERIAL NOT NULL,
    "titleTeam" TEXT NOT NULL,
    "userId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TB_TEAMS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_POKEMONS" (
    "id" SERIAL NOT NULL,
    "pokemonId" INTEGER NOT NULL,
    "teamId" INTEGER NOT NULL,
    "species" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TB_POKEMONS_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TB_USERS_email_key" ON "TB_USERS"("email");

-- AddForeignKey
ALTER TABLE "TB_TEAMS" ADD CONSTRAINT "TB_TEAMS_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TB_USERS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_POKEMONS" ADD CONSTRAINT "TB_POKEMONS_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "TB_TEAMS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
