-- CreateTable
CREATE TABLE "TB_POKEMONS" (
    "id" SERIAL NOT NULL,
    "pokemonId" INTEGER NOT NULL,
    "teamId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TB_POKEMONS_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "TB_POKEMONS" ADD CONSTRAINT "TB_POKEMONS_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "TB_TEAMS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
